version: '3.7'

services:
  db:
    image: postgres:14.1-alpine
    container_name: webtronics-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
  api:
    build: .
    container_name: webtronics-api
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis:6.2.6-alpine
    container_name: webtronics-redis
    restart: unless-stopped
    ports:
      - "6379:6379"