"""add ondelete cascade on fk's

Revision ID: ebcca9822433
Revises: e337ed1f97d7
Create Date: 2023-07-09 02:53:53.589830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebcca9822433'
down_revision = 'e337ed1f97d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dislike_post_id_fkey', 'dislike', type_='foreignkey')
    op.create_foreign_key(None, 'dislike', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('like_post_id_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_dislikes_dislike_id_fkey', 'users_dislikes', type_='foreignkey')
    op.drop_constraint('users_dislikes_user_id_fkey', 'users_dislikes', type_='foreignkey')
    op.create_foreign_key(None, 'users_dislikes', 'dislike', ['dislike_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_dislikes', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_dislikes', type_='foreignkey')
    op.drop_constraint(None, 'users_dislikes', type_='foreignkey')
    op.create_foreign_key('users_dislikes_user_id_fkey', 'users_dislikes', 'user', ['user_id'], ['id'])
    op.create_foreign_key('users_dislikes_dislike_id_fkey', 'users_dislikes', 'dislike', ['dislike_id'], ['id'])
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_post_id_fkey', 'like', 'post', ['post_id'], ['id'])
    op.drop_constraint(None, 'dislike', type_='foreignkey')
    op.create_foreign_key('dislike_post_id_fkey', 'dislike', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
