"""add user additional model

Revision ID: abfa9e56f174
Revises: 7a47680d3e89
Create Date: 2023-07-09 19:54:15.581532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abfa9e56f174'
down_revision = '7a47680d3e89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useradditional',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('time_zone', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('email_status', sa.String(length=100), nullable=True),
    sa.Column('email_score', sa.SmallInteger(), nullable=True),
    sa.Column('email_disposable', sa.Boolean(), nullable=True),
    sa.Column('email_gibberish', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useradditional_id'), 'useradditional', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useradditional_id'), table_name='useradditional')
    op.drop_table('useradditional')
    # ### end Alembic commands ###
