"""add ondelete cascade on userslikes fk

Revision ID: 7a47680d3e89
Revises: ebcca9822433
Create Date: 2023-07-09 02:56:15.126756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a47680d3e89'
down_revision = 'ebcca9822433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_likes_user_id_fkey', 'users_likes', type_='foreignkey')
    op.drop_constraint('users_likes_like_id_fkey', 'users_likes', type_='foreignkey')
    op.create_foreign_key(None, 'users_likes', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_likes', 'like', ['like_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_likes', type_='foreignkey')
    op.drop_constraint(None, 'users_likes', type_='foreignkey')
    op.create_foreign_key('users_likes_like_id_fkey', 'users_likes', 'like', ['like_id'], ['id'])
    op.create_foreign_key('users_likes_user_id_fkey', 'users_likes', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
